spring:
  application:
    name: rag-chatbot

  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

# 外部 API 配置
api:
  huggingface:
    url: http://127.0.0.1:8000

  chat:
    url: https://www.chataiapi.com
    token:
    model: gemini-2.5-flash

server:
  port: 8080


logging:
  level:
    com.example.ragchatbot: DEBUG
    org.springframework.web: DEBUG

# ===============================================================
# ==                      【MyBatis 最终配置】                    ==
# ===============================================================
mybatis:
  # 这个配置项保持不变，用于指定XML文件的位置
  mapper-locations: classpath:mapper/*.xml

  # 【核心新增】指定扫描自定义TypeHandler的包
  type-handlers-package: com.example.ragchatbot.typehandler
